import Navbar from "@/components/shared/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// import { Inter } from 'next/font/google'
// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
// })

export const metadata = {
  title: "Next App 1",
  description: "Generated by create next app",
};

import { Roboto } from 'next/font/google'
const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
})



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        <h1></h1>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
